# Funding/sponsorship configuration for MalachiMQ
# Documentation: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# GitHub Sponsors (replace with your username)
github: HectorIFC

# Patreon (uncomment and add your username if you use it)
# patreon: your-username

# Open Collective (uncomment if the project has a page)
# open_collective: malachimq

# Ko-fi (uncomment and add your username if you use it)
# ko_fi: your-username

# Buy Me a Coffee (uncomment and add your username if you use it)
# buy_me_a_coffee: your-username

# Liberapay (uncomment and add your username if you use it)
# liberapay: your-username

# IssueHunt (uncomment if you use it)
# issuehunt: HectorIFC/malachimq

# Polar (uncomment if you use it)
# polar: HectorIFC

# Custom links (uncomment and add your links)
# custom: ["https://paypal.me/your-user", "https://your-site.com/donate"]
